# ============================================
# IDENTIDAD
# ============================================
identity:
  name: "Alexandra Barroso"
  title: "Psicóloga Clínica"
  tagline: "Psicóloga Online experta en Ansiedad, Trauma (EMDR) y Salud Perinatal. Terapia personalizada sin desplazamientos."
  subtitle: "Psicoterapia integradora que se adapta a ti"
  credentials: "Psicóloga Colegiada CV-13539 · Universidad Complutense de Madrid"
  location: "Madrid, España"

# ============================================
# CONTACTO
# ============================================
contact:
  # Nota: El teléfono se gestiona en _data/seo.yml

  whatsapp_msg: "Hola Alexandra, me gustaría recibir información sobre tus servicios y contarte mi situación actual para valorar cómo puedes ayudarme."
  email: "contacto@alexandrabarroso.com"
  # instagram: "https://instagram.com/alexandrabarroso.psicologa" # Descomentar para activar
  linkedin: "https://www.linkedin.com/in/alexandrabarrosodiaz/"

# ============================================
# NAVEGACIÓN
# ============================================
nav:
  - text: "Inicio"
    url: "/"
  - text: "Sobre Mí"
    url: "/#sobre-mi"
  - text: "Especialidades"
    url: "/#especialidades"
  - text: "Blog"
    url: "/blog/"
  - text: "Testimonios"
    url: "/#testimonios"
  - text: "FAQ"
    url: "/#faq"
cta_text: "Solicita Valoración"

# ============================================
# HERO
# ============================================
hero:
  title_emotional: "Recupera tu bienestar emocional"
  title_professional: "Psicóloga Clínica especialista Online"
  subtitle: "Entiendo tu sufrimiento. Juntos, lo transformamos."
  cta_primary: "Agenda tu primera sesión"
  cta_secondary: "Conoce mi metodología"
  image: "/assets/images/alexandra-hero.webp"
  frame_style: "rotate"  # Options: rotate, rotate-alt, simple, none

# ============================================
# TRUST BAR (MEDIOS)
# ============================================
trust_bar:
  title: "Experiencia clínica"
  logos:
    - name: "Hospital Arnau de Vilanova"
      image: "/assets/images/logos/arnau.svg"
    - name: "Hospital Vithas Valencia al Mar"
      image: "/assets/images/logos/vithas.svg"

# ============================================
# SOBRE MÍ
# ============================================
about:
  title: "Hola, soy Alexandra"
  image: "/assets/images/alexandra-about.webp"
  bio_intro: "Algunos dicen que la psicología te elige. A mí me eligió."
  bio_main: |
    La curiosidad por comprender **por qué sufrimos** y cómo podemos dejar de hacerlo me ha llevado a dedicar más de 15 años al estudio y trabajo en el ámbito de la Psicología Clínica.
    
    Trabajo desde una orientación **integradora** con un enfoque **humanista, personal y cercano**. Mi terapia se adapta a ti, no al revés: selecciono las técnicas más efectivas de cada enfoque para crear un tratamiento a tu medida.
  bio_boutique: "Sin intermediarios. Sin algoritmos. Solo tú y yo, trabajando en equipo para reescribir las narrativas que te causan sufrimiento."
  cta_more: "Conoce mi historia completa"
  cta_more_url: "/sobre-mi/"
  signature: "Alexandra"

# ============================================
# ¿PARA QUIÉN ES?
# ============================================
for_whom:
  title: "¿Te identificas?"
  subtitle: "Mi terapia está diseñada para ti si..."
  profiles:
    - icon: "heart"
      title: "Vives con ansiedad o miedos"
      description: "Si la preocupación constante o el pánico te impiden disfrutar del presente."
    - icon: "cloud"
      title: "Atraviesas un duelo o ruptura"
      description: "Una pérdida, una separación, o el fin de una etapa que necesitas procesar."
    - icon: "refresh"
      title: "Intentas ser madre"
      description: "Acompañamiento emocional en procesos de infertilidad, reproducción asistida o pérdidas gestacionales."
    - icon: "briefcase"
      title: "Buscas entenderte mejor"
      description: "Problemas de autoestima, relaciones conflictivas o patrones que se repiten en tu vida."


# ============================================
# TESTIMONIOS
# ============================================
testimonials:
  title: "Lo que dicen de mí"
  subtitle: "Experiencias reales de transformación"
  items:
    - text: "Después de años buscando a la profesional adecuada, encontré en Alexandra exactamente lo que necesitaba. Su enfoque cercano pero profesional me ayudó a superar mi ansiedad laboral en pocos meses."
      author: "Directiva de marketing"
      age: "42 años"
    - text: "Como madre, ver la transformación de mi hija ha sido increíble. Alexandra conectó con ella desde la primera sesión y le dio herramientas que usa a diario."
      author: "Madre de adolescente"
      age: "48 años"
    - text: "La flexibilidad de las sesiones online fue clave para poder compatibilizarlo con mi trabajo. Alexandra me ayudó a poner límites sanos y recuperar mi equilibrio."
      author: "Emprendedora"
      age: "35 años"

# ============================================
# FAQ
# ============================================
faq:
  title: "Preguntas Frecuentes"
  subtitle: "Todo lo que necesitas saber antes de empezar"
  items:
    - question: "¿Es efectiva la terapia online?"
      answer: "Absolutamente. Numerosos estudios científicos demuestran que la terapia online tiene la misma efectividad que la presencial. Además, ofrece ventajas como mayor flexibilidad horaria, eliminación de desplazamientos y la comodidad de realizarla desde tu espacio seguro."
    - question: "¿Cuánto dura una sesión ?"
      answer: "Las sesiones tienen una duración de 50 minutos."
    - question: "¿Cómo funciona el pago?"
      answer: "El pago se realiza por transferencia bancaria o mediante un enlace seguro con tarjeta de crédito/débito. Recibirás la factura correspondiente tras cada sesión."
    - question: "¿Qué diferencia hay con otras plataformas de psicología online?"
      answer: "A diferencia de las plataformas masivas donde te asignan un profesional según disponibilidad, aquí trabajarás directamente conmigo. No hay intermediarios, algoritmos ni rotación de psicólogos. Es un servicio boutique donde priorizo la calidad sobre la cantidad."
    - question: "¿Cómo es la primera sesión?"
      answer: "El proceso comienza con una **llamada telefónica** donde me cuentas tu situación y valoro si soy la profesional adecuada para ti. Si es así, agendaremos la primera sesión de terapia para iniciar el tratamiento. Si no, te derivaré al especialista que crea que mejor pueda ayudarte."
    - question: "¿Qué necesito para las sesiones online?"
      answer: "Solo necesitas un dispositivo con cámara y micrófono (ordenador, tablet o móvil), conexión a internet estable, y un espacio privado donde te sientas cómoda. Utilizamos plataformas seguras y cifradas para garantizar la confidencialidad."
    - question: "¿Con qué frecuencia tendremos las sesiones?"
      answer: "Al inicio, lo más recomendable es una frecuencia semanal o quincenal para generar inercia terapéutica. A medida que avancemos y consigamos objetivos, espaciaremos las sesiones a mensuales de seguimiento hasta dar alta."
    - question: "¿Cuánto tiempo durará mi terapia?"
      answer: "Es difícil predecirlo, ya que cada persona tiene su ritmo y cada caso es único. Mi objetivo es que puedas ser autónoma lo antes posible."
    - question: "¿Qué pasa si tengo que cancelar una sesión?"
      answer: "Entiendo los imprevistos. Solo te pido que me avises con al menos 24 horas de antelación para poder reorganizar la agenda y ofrecer ese hueco a otra persona que lo necesite. Las cancelaciones con menos tiempo implican el abono de la sesión."
    - question: "¿Es segura y confidencial la terapia online?"
      answer: "Totalmente. La confidencialidad es sagrada en mi consulta. Utilizo plataformas de videollamada encriptadas (Google Meet, Skype, Zoom) y seguras que cumplen estrictamente con la Ley de Protección de Datos, garantizando que nuestro espacio sea tan privado como una consulta presencial."

# ============================================
# ESPECIALIDADES (SEO)
# ============================================
specialties:
  title: "Áreas de Intervención"
  subtitle: "Abordaje especializado en problemas complejos"
  categories:
    - title: "Salud de la Mujer"
      items:
        - name: "Psicoterapia Perinatal"
          desc: "Acompañamiento en embarazo, parto, posparto y vínculo madre-bebé."
        - name: "Infertilidad"
          desc: "Apoyo emocional en la búsqueda de embarazo y reproducción asistida."
        - name: "Duelo Gestacional y Perinatal"
          desc: "Acompañamiento en pérdidas durante el embarazo o tras el nacimiento."
        - name: "Sexualidad"
          desc: "Abordaje de disfunciones sexuales y acompañamiento en la menopausia."
    - title: "Trauma y Apego"
      items:
        - name: "Terapia EMDR"
          desc: "Procesamiento de estrés postraumático, traumas y experiencias adversas."
        - name: "Estilos de Apego"
          desc: "Sanar heridas vinculares y patrones relacionales inseguros."
        - name: "Autoestima"
          desc: "Fortalecimiento del autoconcepto, la seguridad y la valía personal."
    - title: "Bienestar Emocional"
      items:
        - name: "Trastornos de Ansiedad"
          desc: "Gestión de pánico, crisis de ansiedad, agorafobia y estrés."
        - name: "Depresión y Estado de Ánimo"
          desc: "Abordaje terapéutico de la depresión, distimia y trastorno bipolar."
        - name: "TOC"
          desc: "Tratamiento de obsesiones y compulsiones con técnicas de primera elección."
        - name: "Duelo"
          desc: "Acompañamiento emocional ante pérdidas significativas o rupturas."
        - name: "Trastornos de Personalidad"
          desc: "Abordaje especializado de patologías complejas como el TLP."
    - title: "Neurodivergencia y Regulación"
      items:
        - name: "TDAH en Adultos"
          desc: "Desarrollo de estrategias ejecutivas y regulación emocional."
        - name: "Altas Capacidades"
          desc: "Gestión de la intensidad emocional y dificultades relacionales."
        - name: "Autorregulación Emocional"
          desc: "Técnicas para el manejo de la ira, impulsividad e inestabilidad."

# ============================================
# LEGAL (Datos del responsable)
# ============================================
legal:
  responsable:
    nombre: "Alexandra Barroso"
    nif: "49024563V"
    direccion: "Madrid, España"
    email: "contacto@alexandrabarroso.com"
    colegiado: "Psicóloga Colegiada CV-13539"

# ============================================
# FOOTER
# ============================================
footer:
  copyright: "Alexandra Barroso - Psicóloga Clínica"
  location_seo: "Servicio de Psicología Online desde Madrid, España para todo el mundo"
  legal_links:
    - text: "Aviso Legal"
      url: "/legal"
    - text: "Política de Privacidad"
      url: "/privacidad"
    - text: "Cookies"
      url: "/cookies"
    - text: "Supervisión Profesionales"
      url: "/sobre-mi/#supervision-para-profesionales"
